name: Bouncy Ball Deploy Workflow
run-name: Deployment
on:
  push:
    branches:
      - main

permissions:
  contents: write
  
env:
  baseurl: "https://23-web-teamproject/bouncy-ball/"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
